Reducing should work (theoretically)
shrutiyer/dcomp_assignment4 pull request #2
Opened 2017-04-10 04:16 UTC by shrutiyer

I have set everything up for 

* reducing to start adding as soon as some mapper calls it
* master to keep track of how many mapper tasks still need to be finished
* terminate the reducer factory after n millisec
* right before termination, reducer gives the final count to master

What needs to be done:

* Write the word count to file. I already wrote a function to do that. We just need to call it from somewhere once the last reducer has reported the count back. And we should be done :fireworks: :champagne: 

Note: My IntelliJ was weirding out. It won't compile my code :frowning_face:

2017-04-10 23:39 UTC, davidabrahams requested changes

2017-04-10 23:39 UTC, davidabrahams commented on src/Master.java
> +            while (now < expectedElapsedTime) {
Switch this to a sleep

2017-04-10 23:39 UTC, davidabrahams commented on src/Master.java
> +            j++; i++; mapTaskIndex++;
todo: set a boolean that is if we're still assigning tasks, use it to terminate mappers

2017-04-10 23:39 UTC, davidabrahams commented on src/Master.java
> +            iReducer factory = (iReducer) reg.lookup("reduce_manager");
reg is not correct variable here

2017-04-10 23:39 UTC, davidabrahams commented on src/Master.java
todo: reduce tasks are not being killed yet, only managers

2017-04-10 23:39 UTC, davidabrahams commented on src/Master.java
> +    private void writeWordCountToFile() {
todo: actually call this

2017-04-10 23:51 UTC, shrutiyer commented on src/Master.java
> +            while (now < expectedElapsedTime) {
Done

2017-04-11 00:11 UTC, shrutiyer commented on src/Master.java
> +            iReducer factory = (iReducer) reg.lookup("reduce_manager");
Done

2017-04-11 00:12 UTC, shrutiyer commented on src/Master.java
Done

2017-04-11 01:38 UTC, merged